[workspace]
members = [
    "crates/*"
]

[workspace.dependencies]
tokio = { version = "1.21" }

[package]
name = "archiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html