[workspace]
members = [
    "crates/*"
]

[workspace.dependencies]
futures = "0.3"
tokio = "1.21"
thiserror = "1.0"

[package]
name = "archiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html